# Generated by Django 2.2.5 on 2020-11-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='images/<django.db.models.fields.AutoField>'),
        ),
    ]
