# Generated by Django 2.2.5 on 2020-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201109_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemdescription',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='itemname',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='images/Items'),
        ),
    ]
