# Generated by Django 2.2.5 on 2020-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201109_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='purchaseCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='itemid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='publisheditem',
            name='userid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='itemid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='userid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='itemid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='userid',
            field=models.IntegerField(db_index=True),
        ),
    ]
