# Generated by Django 2.2.5 on 2020-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201109_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
                ('categoryimage', models.ImageField(upload_to='images/Categories')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='categoryid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
