# Generated by Django 2.2.5 on 2020-11-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201109_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_index=True)),
                ('itemid', models.IntegerField(db_index=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
