# Generated by Django 2.2.5 on 2020-11-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
